apiVersion: config.kubernetes.io/v1alpha1
kind: ResourceList
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: example
      namespace: example
      annotations:
        kpt.seek.com/hash-dependency: ConfigMap/my-config-map
    spec: {}
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: my-config-map
      namespace: example
    data: {}
