apiVersion: config.kubernetes.io/v1alpha1
kind: ResourceList
items:
- apiVersion: kpt.dev/v1alpha1
  kind: Kptfile
  metadata:
    name: test
  openAPI:
    definitions:
      io.k8s.cli.setters.hosts:
        type: array
        items:
          type: string
        x-k8s-cli:
          setter:
            name: hosts
            listValues:
            - "example.com"
            - "dead.beef"
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: test
    namespace: test-system
  spec:
    hosts: # {"$kpt-set":"hosts"}
    - "placeholder.com"
    gateways:
    - external-gateway
    - internal-gateway
    http:
    - route:
      - destination:
          host: test.destination.com
      timeout: 30s
