apiVersion: config.kubernetes.io/v1alpha1
kind: ResourceList
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: example
    namespace: example
    annotations:
      kpt.seek.com/hash-dependency/config-map: ConfigMap/my-config-map
      kpt.seek.com/hash-dependency/another-type: AnotherType/another-type
      ConfigMap/my-config-map: 'dfa6c3c082ad3ee44f29b13328af93f4c00e9438e93f7c8b5a58dd389cd491e6'
      AnotherType/another-type: '86db829e5f05670ba1162010566a09090bedd562d9f7b95dd94cb98447978f3a'
  spec: {}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: my-config-map
    namespace: example
  data: {}
- apiVersion: custom-namespace.seek.com/v1
  kind: AnotherType
  metadata:
    name: another-type
    namespace: example
  data: {}
