apiVersion: config.kubernetes.io/v1alpha1
kind: ResourceList
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: example
    namespace: example
    annotations:
      kpt.seek.com/hash-dependency/config-map: ConfigMap/my-config-map
      kpt.seek.com/hash-dependency/another-type: AnotherType/another-type
  spec: {}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: my-config-map
    namespace: example
  data: {}
- apiVersion: custom-namespace.seek.com/v1
  kind: AnotherType
  metadata:
    name: another-type
    namespace: example
  data: {}
